# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a8361bc0d0919b5f67b0d759fb37fd568ad037221d28702f3eba27d89b2ae48b763b0939a0a2acf60a0b721209714a9912a74af271a7104bcba9ff3cc6f41f0

test:
  secret_key_base: 93674c34ff542266341a00a645fd66b3849b7e0da6512521423d545f3e5ca27944a3081b0f644feb10bfa91fd30f9350421850ae78622179e875e2b75077f83c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
